name: 'Changelog Generator'
description: 'Github action that creates a changelog upon PR opening. The changelog will contain all the commit messages grouped by type and change level (major, minor, patch).'
author: 'sinisag'
branding:
  icon: 'file-text'  
  color: 'white'
inputs:
  token:
    required: true
    description: 'As provided by Github Actions'
runs:
  using: 'node10'
  main: 'index.js'